[profile.default]
src = "src"
fuzz = { runs = 10000 }

out = "out"
libs = ["lib"]
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
fs_permissions = [
    { access = "read-write", path = "/home/asyam321/Project/RetroPick/RetroPick/.cursor/debug.log" }
]
